language: node_js
node_js:
- lts/*
cache:
  apt: true
  directories:
  - node_modules
before_install:
- composer config --global github-oauth.github.com "$GITHUB_TOKEN"
install:
- npm install
script:
- npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: lnTRs7aS7HzPBaE0XmIn/Msf9HEZSjDnLBLLoSIQ5M9iycDfSq36yscpEHg49CVqZ3nhfJmvL5f14Ay0XHYqgHPi1eN1SDUl6m0e/nQzMiDJBVxe+MoyKgJHxcG+P5/Xamtc3aFFCQfgPGtLyJMuiZcC08nMOZKWCtYtUD45QVz0a/vFn7SB3k+/aZa2E3Kc41HSRC3si/hZSEmlWRVVfCjWxIYpszuGqowJ4S3BgX9RV9QbYYFUzA3ILXvCSRpVWkgoyPRGJBRlvyTVy/5JvLf9MaCdTpJFbFCgiw3gTheFTAMOCtwU6cQnIMBfzAuE/SiGsylruesc7NhQDIEEJGzW0+9CUlecBi8Zu2yi5cb2pHc9iUqf+oczP2M7Gwym6Y9G2vprA0hvgK49oTEsG9rE7855HM9objrLVVTldwAgw0/7DH9ZL9dOFed1otoulPuOPK/r2uPu3pSQLj7yJGV4b3zw8y+kNNk7pSSKhjRjhJ9AK+NSrUPlYqLRtQ2LlXkwgERe1VWZ85AbqhZwUkz1jSGyaUbjzFVWj1lSN/wxDspvRQqTnsqIEAeTYoZsnN6vhNOz6ZcGQQRq9jfvdjNqdBQt7j0CDIXfijOtDctdnMxVxwyYJxEpSrWUaJhMuHkaxR0fwR3vtQ5FjWgiDE1HHVRoe0cdE6Yy9lmxyIg=
