language: node_js
node_js:
- lts/*
cache:
  apt: true
  directories:
  - node_modules
before_install:
- composer config --global github-oauth.github.com "$GITHUB_TOKEN"
install:
- npm install
script:
- npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: jmIPsoOb5QIvOk5kB4PWFMgvNOXQVqqn+I9sT0Ch/vwdE8Y0v+tW8qk7eiUuRjV+x8u+JgN2TFzkG1WqPlo6MI1a0roOYuF/FHxe+Ph/m5/Qq/iCHhY9lnBPxYDgQPt5wskTw/DuVsgtyzKfZGGVcrcuy4Fwm7iyU61acDXtDkug7gXMHtuhk93TgdqC1hfJiZ+0RIHrJPr8vPplRN2QiWUZ6y+N+jt9B7kjk9lne5mG6aglEcr6WNXeFCzvZFJYgiR1ji1KpzC7iw8XGW4SlSv9m+20x+uqJvgPSianCkHXvOCWFCL7mNbIHHKxrcBn6x8m6YIQDiXNWwGYhY9m44fNYG4wNxghrW1NPT/T8POHHsbsD16XYb/AKViUcJOtfoJrUIcFvEuh9QhqZSOcDF00zYcrGl+pHiMCyzCXludUXaqAmB+vnGtfCB7q3Pp7oCPopYKgTPWn5vOk5NUVBwt2GvamP6t7hi2D20ixKFMQeBjjuJHo0du84HK4Yq1hvJiTM9lVk3/qk99/onUcpmB2H3kpJz0I9q5YShqcnoHllxvMKttmqz+kgHjlpPLEgaXh4JAY6G05Il+6eP4oAIPwLOdQGt+nDXX0QZ+T06BKNF359/FE5F67OAKecvaR68FTq7NcRBwUzv0XIlEVoYeNoVgcELKWXHbcFklr/eA=
